api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework import routers

from .rest_views import (ClinicProcedureViewSet, ProcedureViewSet,
                        ClinicRelationTreatmentViewSet)

router = routers.SimpleRouter(trailing_slash=False)
router.register(r'clinic-procedures', ClinicProcedureViewSet)
router.register(r'procedures', ProcedureViewSet)
router.register(r'treatment-categories', ClinicRelationTreatmentViewSet)

urlpatterns = patterns(
    "api.views",
    url(r"^get_cities/$", 'get_cities', name='get_cities'),
    url(r"^get_looking_for/$", 'get_looking_for', name='get_looking_for'),
    url(r"^request_password/$", 'request_password', name='request_password'),
    url(r'^', include(router.urls))
)

collaborator/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import patterns, url
from .rest import PricesRest, TreatmentRest, DoctorRest, OverviewRest, ProcedureRest
from .rest import ComplementaryServiceRest, SpecialPromotionRest


#Collaborator url resolves
urlpatterns = patterns(
    "collaborator.views",
    url(r"^$", 'general', name='general'),
    url(r"^overview/$", 'overview', name='overview'),
    url(r"^gallery/$", 'gallery', name='gallery'),
    url(r"^location/$", 'location', name='location'),
    url(r"^doctors/$", 'doctors', name='doctors'),
    url(r"^prices/$", 'prices', name='prices'),
    url(r"^about/$", 'about', name='about'),
    url(r"^select_clinic/(?P<id>\d+)/$", 'select_clinic', name='select_clinic'),
    url(r"^change_clinic/$", 'change_clinic', name='change_clinic'),
    url(r"^change_required/$", 'send_change_required', name='change_required'),
    url(r"^add-treatment/$", 'add_treatment', name='add_treatment'),
)

#API responses
urlpatterns += patterns(
    "collaborator.api",
    url(r"^change_password/$", 'change_password', name='change_password'),
    url(r"^add_photo/$", 'add_photo', name='add_photo'),
    url(r"^del_photo/$", 'del_photo', name='del_photo'),
    url(r"^alter_about/$", 'alter_about', name='alter_about'),
    url(r"^api/render_photos/$", 'render_photos', name='render_photos'),
    url(r"^api/add_to_front/$", 'add_to_front', name='add_to_front'),
    url(r"^api/save_images/$", 'save_images', name='save_images'),
    url(r"^api/render_heade_images/$", 'render_heade_images', name='render_heade_images'),
    url(r"^api/render_overview/$", 'render_overview', name='render_overview'),
    url(r"^api/select_testimonial/$", 'select_testimonial', name='select_testimonial'),
    url(r"^api/save_overview/$", 'save_overview', name='save_overview'),
    url(r"^api/save_location/$", 'save_location', name='save_location'),
    url(r"^api/save_doctor/$", 'save_doctor', name='save_doctor'),
    url(r"^api/delete_doctor/$", 'delete_doctor', name='delete_doctor'),
    url(r"^api/render_doctors/$", 'render_doctors', name='render_doctors'),
    url(r"^api/save_treatment/$", 'save_treatment', name='save_treatment'),
    url(r"^api/delete_treatment/$", 'delete_treatment', name='delete_treatment'),
    url(r"^api/save_price/$", 'save_price', name='save_price'),
    url(r"^api/delete_price/$", 'delete_price', name='delete_price'),
)

#RESTful url responses
urlpatterns += patterns(
    "",
    url(r"^rest/price/(?P<id>\d+)$", login_required(PricesRest.as_view()), name='price_details'),
    url(r"^rest/price$", login_required(PricesRest.as_view()), name='price'),

    url(r"^rest/treatment/(?P<id>\d+)$", login_required(TreatmentRest.as_view()), name='treatment_details'),
    url(r"^rest/treatment$", login_required(TreatmentRest.as_view()), name='treatment'),

    url(r"^rest/procedure/(?P<id>\d+)$", login_required(ProcedureRest.as_view()), name='procedure_details'),
    url(r"^rest/procedure$", login_required(ProcedureRest.as_view()), name='procedure'),

    url(r"^rest/doctor/(?P<id>\d+)$", login_required(DoctorRest.as_view()), name='doctor_details'),
    url(r"^rest/doctor$", login_required(DoctorRest.as_view()), name='doctor'),

    url(r"^rest/overview$", login_required(OverviewRest.as_view()), name='rest_overview'),

    url(r"^rest/complementary_service/(?P<id>\d+)$", login_required(ComplementaryServiceRest.as_view()), name='complementary_service'),
    url(r"^rest/complementary_service$", login_required(ComplementaryServiceRest.as_view()), name='complementary_service'),

    url(r"^rest/special_promotion/(?P<id>\d+)$", login_required(SpecialPromotionRest.as_view()), name='special_promotion'),
    url(r"^rest/special_promotion$", login_required(SpecialPromotionRest.as_view()), name='special_promotion'),

    url(r"^rest/testimonial$", "collaborator.rest.testimonial", name='testimonial'),

    url(r"^rest/update_position$", "collaborator.rest.update_position", name='update_position'),

)

config/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from mezzanine.urls import urlpatterns as mezzanine_urlpatterns
admin.autodiscover()

urlpatterns = patterns(
    "",
    url("^$", "sanico.views.home", name="home"),

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
    url("^widget/", include("widget.urls")),
    url("^validate/", include("libs.validationlink.urls", namespace='validation')),
    url("^formview/", include("libs.formview.urls", namespace='formview')),

    url("^profile/", include("profile.urls")),
    url("^collaborator/", include("collaborator.urls", namespace="collaborator")),
    url("^podcast/", include("podcast.urls")),

    # Django API RESTful Framework
    url("^api/", include("api.urls")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Sanico app URLS
    url("^", include('sanico.urls')),

    # Mezzanine's apps urls
    url("^", include(mezzanine_urlpatterns)),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

collaborator/models.py
from django.db import models


#

collaborator/forms.py
from django import forms
from django.forms import ModelForm
from profile.models import Clinic


class CollaboratorAboutForm(ModelForm):
    class Meta:
        model = Clinic
        fields = [
            'about', 'open_since', 'personal_checks', 'traveler_checks',
            'cash', 'mastercard', 'visa', 'american_express', 'discover',
            'paypal', 'money_order', 'wire_transfer', 'cashier_check',
            'english', 'spanish', 'french', 'japanese', 'italian', 'russian',
            'mandarin', 'portuguese', 'german']

    about = forms.CharField(required=False)
    open_since = forms.CharField(required=False)

collaborator/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.utils import simplejson as json
from mezzanine.pages.models import Page
from profile.models import Clinic, OpeningHour, ClinicPhoto, Review, Location
from sanico.models import SanicoUser
from sanico.email import SendEmail
from .helpers import get_session_clinic


def clinic_session(function_request):
    def clinic_session_callback(request):
        try:
            if not request.session['clinic']:
                clinics = Clinic.objects.filter(user=request.user.id)

                if clinics.count() == 1:
                    request.session['clinic'] = list(clinics)[0].id
                else:
                    request.session['clinic'] = None
        except KeyError:
            request.session['clinic'] = None
        return function_request(request)
    return clinic_session_callback


def collaborator_view(request, template, context={}):
    try:
        page = Page.objects.with_ascendants_for_slug("collaborator")[0]
    except:
        raise Http404

    user = SanicoUser.objects.get(id=request.user.id)

    context["user"] = user
    context["clinic"] = get_session_clinic(request)
    context["clinics"] = Clinic.objects.filter(user=user.id)

    extra_context = RequestContext(request)
    setattr(extra_context, "page", page)
    return render_to_response(
        template, context, context_instance=extra_context)


@login_required(login_url='/login/')
@clinic_session
def about(request):
    opening_hours = OpeningHour.objects.filter(
        clinic=request.session['clinic'])

    return collaborator_view(
        request, "collaborator/about.html", {
            'opening_hours': opening_hours
        })


@login_required(login_url='/login/')
@clinic_session
def general(request):
    return collaborator_view(request, 'collaborator/general.html')


@login_required(login_url='/login/')
@clinic_session
def overview(request):
    reviews = Review.objects.filter(
        clinic=request.session['clinic'], enable=True)

    reviews_num = reviews.count()
    photos_num = ClinicPhoto.objects.filter(
        clinic=request.session['clinic']).count()

    return collaborator_view(
        request, 'collaborator/overview.html', {
            'reviews': reviews,
            'reviews_num': reviews_num,
            'photos_num': photos_num
        })


@login_required(login_url='/login/')
@clinic_session
def gallery(request):
    context = {
        'photos': ClinicPhoto.objects.filter(
            clinic=request.session['clinic'])
    }
    return collaborator_view(request, 'collaborator/gallery.html', context)


@login_required(login_url='/login/')
@clinic_session
def location(request):
    try:
        location = Location.objects.get(clinic=request.session['clinic'])
    except:
        location = None
    context = {'location': location}
    return collaborator_view(request, 'collaborator/location.html', context)


@login_required(login_url='/login/')
@clinic_session
def doctors(request):
    return collaborator_view(request, 'collaborator/doctors.html')


@login_required(login_url='/login/')
@clinic_session
def prices(request):
    try:
        location = Location.objects.get(clinic=request.session['clinic'])
    except:
        location = None
    context = {'location': location}
    return collaborator_view(request, 'collaborator/prices.html', context)


@login_required(login_url='/login/')
def select_clinic(request, id):
    try:
        request.session['clinic'] = Clinic.objects.get(user=request.user.id, id=id).id
    except Clinic.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse("collaborator:general"))


@login_required(login_url='/login/')
def change_clinic(request):
    try:
        request.session['clinic'] = None
    except Clinic.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse("collaborator:general"))


@login_required(login_url='/login/')
def add_treatment(request):
    email = SendEmail()
    email.set_recipes(['accounts@sanimedicaltourism.com'])
    email.notify_message(
        "[CINIC TREATMENT REQUIRED]",
        "emails/required_treatment.html", {
            'clinic': get_session_clinic(request),
            'name': request.GET.get('name'),
            'description': request.GET.get('description')
        })

    success = email.send()
    return HttpResponse(
        json.dumps({'success': success}), mimetype="application/json")


@login_required(login_url='/login/')
@clinic_session
def send_change_required(request):
    email = SendEmail()
    email.set_recipes(['accounts@sanimedicaltourism.com'])
    email.notify_message(
        "[PROFILE CHANGE REQUIRED]",
        "emails/profile_change_required.html",
        {'clinic': get_session_clinic(request)})

    success = email.send()
    return HttpResponse(
        json.dumps({'success': success}), mimetype="application/json")

templates/collaborator/base_page.html
{% extends 'base.html' %}
{% load mezzanine_tags widget_tags future i18n staticfiles %}

{% block meta_title %}{{ page.meta_title }}{% endblock %}

{% block extra_head %}
    {% block page_name %}
    <meta name="page" data="" />
    {% endblock %}
    <meta name="media_url" data="{{MEDIA_URL}}">
{% endblock %}

{% block extra_js %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
<script src="{% static 'sanico/js/restangular.js' %}"></script>
<script src="{% static 'sanico/js/collaborator/application.js' %}"></script>
<script src="{% static 'sanico/js/collaborator/script.js' %}"></script>
<script src="{% static 'sanico/js/collaborator/edit.js' %}"></script>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{{ STATIC_URL }}sanico/css/collaborator.css" />
{% endblock %}

{% block body %}
  <header class="header-collaborator">
    <div class="container">
      <div class="row">
        <h1 class="span2 logo-collaborator">
          <a href="/">
            <img src="{{ STATIC_URL }}sanico/img/sanico-collaborator.png" alt="">
          </a>
        </h1>
        <div class="span4 offset6">
          <ul class="user-bar">
            <!-- <li>{% trans "Welcome" %}&nbsp;<span>{{ user.first_name }}</span></li> -->
            {% if clinic %}
            <li><span>{{ clinic.name }}</span></li>
            <li><span><a href="{{clinic.get_absolute_url}}" target="_blank">Ver Perfil</a></span></li>
            {% endif %}
            <li><a href="{% url 'process_logout' %}">Cerrar sesión</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
  <!-- Content -->
  <section class="container">
      <div class="row">
        <!-- Sidebar -->
        <aside  class="span3 sidebar">
          <div class="sidebar-collaborator">
              <ul class="nav nav-list">
                <!-- class="active" -->
                {% if request.session.clinic != None %}
                <li data="general">
                  <a href="{% url 'collaborator:general' %}">Información General</a>
                </li>
                <li data="overview">
                  <a href="{% url 'collaborator:overview' %}">Overview</a>
                </li>
                <li data="about">
                  <a href="{% url 'collaborator:about' %}">About Us</a>
                </li>
                <li data="gallery">
                  <a href="{% url 'collaborator:gallery' %}">Gallery</a>
                </li>
                <li data="prices">
                  <a href="{% url 'collaborator:prices' %}">Prices</a>
                </li>
                <li data="doctors">
                  <a href="{% url 'collaborator:doctors' %}">Doctors</a>
                </li>
                <li data="location">
                  <a href="{% url 'collaborator:location' %}">Location</a>
                </li>
                <li data="">
                  <a href="{% url 'collaborator:change_clinic' %}">Cambiar clinica</a>
                </li>
                {% else %}
                <li data="select">
                  <a href="#!">Selecciona tu clinica</a>
                </li>
                {% endif %}
              </ul>
            </div>
        </aside>
        <!-- /Sidebar -->
        <!-- Edit Section -->
        {% if request.session.clinic != None %}
          {% block edit_section %}{% endblock%}
        {% else %}
          {% if clinics.count > 0 %}
            {% include "collaborator/choice_clinic.html" %}
          {% else %}
            {% include "collaborator/sorry.html" %}
          {% endif %}
        {% endif %}

        <!-- /Edit Section -->
      </div>
  </section>
  <!-- /Content -->
{% endblock %}

{% block lateral_buttons %}{% endblock %}
{% block alert_block %}{% endblock %}

templates/collaborator/choice_clinic.html
{% load mezzanine_tags i18n %}

{% block page_name %}
<meta name="page" data="select" />
{% endblock %}

<div class="span9 profile">
    <div class="editor-header">
      <h2>Elige una clinica</h2>
    </div>

    <div class="row">
        {% for clinic in clinics %}
        <div class="clinic-image">
            <a href="{% url 'collaborator:select_clinic' clinic.id %}">
                <img src="{{MEDIA_URL}}{% thumbnail clinic.image_profile 180 180 %}" alt="">
            </a>
            <div class="clinic-name">{{clinic.name}}</div>
        </div>
        {% endfor %}
    </div>
</div>

templates/collaborator/doctors.html
{% extends 'collaborator/base_page.html' %}
{% load mezzanine_tags i18n %}

{% block extra_head %}{{block.super}}
<meta name="render_doctors_url" data="{% url 'collaborator:render_doctors' %}">
<meta name="delete_doctor_url" data="{% url 'collaborator:delete_doctor' %}">
{% endblock %}

{% block extra_js %}{{block.super}}
<script type="text/javascript" src="{{STATIC_URL}}sanico/js/collaborator/doctors.js"></script>
{% endblock %}

{% block page_name %}
<meta name="page" data="doctors" />
<meta name="static_url" data="{{STATIC_URL}}">
{% endblock %}

{% block edit_section %}
{% csrf_token %}
{% verbatim %}
<div class="span9 doctors edit-section" ng-app="CollaboratorApp" ng-controller="DoctorsController">
    <div class="profile-title">
      <h2>Doctores</h2>
    </div>
    <div class="row">
        <div class="doctors-list"></div>
        <!-- Doctor -->
        <article class="span9 doctor-block" ng-repeat="doctor in doctors">
          <form method="post" action="{{get_form_url(doctor)}}" ng-model="doctor" jform="doctor">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" />
            <input type="hidden" name="position" value="0" />
            <div class="span7">
              <input class="btn btn-blue lt-btn" type="submit" value="Guardar" />
              <span class="btn btn-red lt-btn" ng-click="del_doctor(doctor)" >Borrar</span>
              <img src="{{static_url}}sanico/img/loading_2.gif" class="doctor-info-loading" style="display:none"/>
              <header class="dental-bg" ng-init="doctor.name_edited=!bool(doctor.id)">
                  <h3 ng-hide="doctor.name_edited" ng-click="doctor.name_edited=true">{{doctor.first_name}} {{doctor.last_name}}</h3>
                  <input type="text" name="first_name" class="input-edit-large" placeholder="Nombre" ng-model="doctor.first_name" ng-show="doctor.name_edited" />
                  <input type="text" name="last_name" class="input-edit-large" placeholder="Apellido" ng-model="doctor.last_name" ng-show="doctor.name_edited" />
              </header>
              <div class="doctor-info">
                <p ng-init="doctor.education_edited=!bool(doctor.id)">
                  Education: <span ng-hide="doctor.education_edited" ng-click="doctor.education_edited=true">{{doctor.education}}</span>
                  <input type="text" name="education" class="input-edit-xlarge" ng-model="doctor.education" ng-show="doctor.education_edited" />
                </p>
                <p ng-init="doctor.specialisations_edited=!bool(doctor.id)">
                  Specialisations: <span ng-hide="doctor.specialisations_edited" ng-click="doctor.specialisations_edited=true">{{doctor.specialisations}}</span>
                  <input type="text" name="specialisations" class="input-edit-xlarge" ng-model="doctor.specialisations" ng-show="doctor.specialisations_edited" />
                </p>
                <p ng-init="doctor.languages_edited=!bool(doctor.id)">
                  Languages: <span ng-hide="doctor.languages_edited" ng-click="doctor.languages_edited=true">{{doctor.languages}}</span>
                  <input type="text" name="languages" class="input-edit-xlarge" ng-model="doctor.languages" ng-show="doctor.languages_edited" />
                </p>
                <p>
                  Curriculum (*.pdf, *.doc, *docx): <span>{{doctor.resume|resume}}</span><input type="file" name="resume" id="file-resume">
                </p>
              </div>
            </div>
            <figure class="span2 doctor-photo">
              <img src="{{media_url}}{{doctor.photo}}" width="140" height="200" ng-hide="!bool(doctor.id)" />
              <input type="file" name="photo" id="field-doctor-image" />
            </figure>
          </form>
        </article>
        <!-- /Doctor -->
    </div>
    <div class="span7 add-doctor-content">
      <span class="btn btn-green lt-btn" ng-click="add_doctor()">Agregar Doctor</span>
    </div>
</div>
{% endverbatim %}
{% endblock %}

templates/collaborator/gallery.html
{% extends 'collaborator/base_page.html' %}
{% load mezzanine_tags i18n profile_tags collaborator_tags %}

{% block page_name %}
<meta name="page" data="gallery" />
<meta name="url_add" data="{% url 'collaborator:add_photo' %}" />
<meta name="url_del" data="{% url 'collaborator:del_photo' %}" />
<meta name="url_render" data="{% url 'collaborator:render_photos' %}" />
<meta name="add_to_front" data="{% url 'collaborator:add_to_front' %}" />
{% endblock %}

{% block extra_css %}{{block.super}}
<link rel="stylesheet" href="{{ STATIC_URL }}sanico/css/kendo/kendo.common.min.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}sanico/css/kendo/kendo.default.min.css" />
{% endblock %}

{% block extra_js %}{{block.super}}
<script src="{{ STATIC_URL }}sanico/js/kendo/kendo.all.min.js"></script>
<script src="{{STATIC_URL}}sanico/js/collaborator/edit_gallery.js"></script>
{% endblock %}

{% block edit_section %}
<div class="span9 profile edit-section">
    <div class="editor-header">
      <h2>Gallery</h2>
    </div>
    <div class="add-photo">
      <label for="add-photo">Agregar fotografia</label>
      <input name="photo" type="file"  id="add-photo" />
      {% csrf_token %}
    </div>
    <div class="profile-gallery" id="profile-gallery">
      {% render_coll_photos clinic %}
    </div>
</div>
{% endblock %}

templates/collaborator/overview.html
{% extends 'collaborator/base_page.html' %}
{% load mezzanine_tags i18n %}

{% block page_name %}
  <meta name="page" data="overview" />
{% endblock %}

{% block extra_head %}{{block.super}}
  <meta name="render_heade_images" data="{% url 'collaborator:render_heade_images' %}">
  <meta name="render_overview_url" data="{% url 'collaborator:render_overview' %}">
{% endblock %}

{% block extra_js %}{{block.super}}
<script type="text/javascript" src="{{STATIC_URL}}sanico/js/collaborator/overview.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}sanico/js/collaborator/edit_overview.js"></script>
{% endblock %}

{% block edit_section %}
<div class="span9 profile edit-section" ng-app="OverviewApp" ng-controller="OverviewController">
  <div class="editor-header">
    <h2>Overview</h2>
  </div>
    <div class="editor-overview">
      <div class="results-editor">
        <div class="results-header  sanico-bg results-top-clinic">
          <h3 class="result-title">{{ clinic.name }}</h3>
          <p class="address">{{clinic.city}} / {{clinic.country}}</p>
        </div>

          {% csrf_token %}
          <div class="results-box">
            <!-- image -->
            <figure class="pull-left results-img">
              <img src="{{MEDIA_URL}}{% thumbnail clinic.image_profile 140 140 %}" alt="" id="overview-image" />
              <p>{{photos_num}} Photos</p>
            </figure>
            <!-- image -->
            <div class="results-content">
              <!-- Stars -->
              <div class="results-head">
                <div class="star-holder">
                  <div class="star-rating" itemprop="reviewRating" style="width: {{clinic.get_qualification}}0px"></div>
                </div>
                  <span class="results-meta">({{reviews_num}} {% trans "Patient Reviews" %})</span>
              </div>
              <!-- /Stars -->

              <!-- Description -->
              <div class="results-description">
                <p itemprop="description" class="overview-description">
                  {{clinic.about|striptags|truncatewords_html:20}}
                </p>
                <p>
                  {% verbatim %}
                  <span ng-click="show_popup=true" title="Selecciona un testimonial" class="description-span testimonial-class">Testimonial:&nbsp;</span>
                  <span ng-click="show_popup=true" title="Selecciona un testimonial" class="testimonial-class">
                    {{testimonial|truncate:25}}
                  </span><br>
                  <span class="results-name-review">{{testimonial_name}}</span>
                  {% endverbatim %}
                </p>
                <p>
                  <span class="description-span">{% trans "Language" %}:&nbsp;</span>
                  {% if clinic.english %}English&nbsp;{% endif %}
                  {% if clinic.spanish %}Spanish&nbsp;{% endif %}
                  {{clinic.other}}
                </p>

                {% verbatim %}
                <span ng-hide="edit_offer" ng-click="edit_offer=true">
                  <h4 >{{offer}}</h4>
                </span>
                {% endverbatim %}
                <div>
                  <input type="text" ng-model="offer_edited" class="input-edit-large lt-btn-left" ng-show="edit_offer" size="200">
                  <input type="button" class="btn btn-blue lt-btn-left" ng-click="change_overview()" ng-show="edit_offer" value="Guardar" />
                  <input type="button" class="btn btn-red lt-btn-left" ng-click="cancel()" ng-show="edit_offer" value="Cancelar" />
                </div>
                <a href="#!" class="btn btn-orange right">{% trans "Quote from this Clinic" %}</a>
              </div>
              <!-- /Description -->
            </div>
          </div>

      </div>
      </form>

      <!-- Home banner -->
      <form action="{% url 'collaborator:save_images' %}" method="post" id="images-form" style="display:none">
        {% csrf_token %}
        <input type="file" name="header_image" id="field-header-image" class="file-images" />
        <input type="file" name="profile_image" id="field-profile-image" class="file-images" />
      </form>

      <div class="editor-timeline" id="header-images-content">
        <!-- content profile images  -->
      </div>
      <!-- Home banner -->
    </div>

    <div id="popup" ng-init="show_popup=false" ng-show="show_popup">
      <div class="background-popup"></div>
      <div class="content-popup">
          <div>Seleccione un testimonial</div>
          <div class="select-review">
            <form action="{% url 'collaborator:select_testimonial' %}" method="post" id="testimonial-form">
              {% csrf_token %}
              <table class="table-reviews">
              {% for review in reviews %}
                <tr>
                  {% if review.for_testimonial %}
                  <span ng-init="review_selected={{review.id}}"></span>
                  {% endif %}
                  <td><input type="radio" ng-model="review_selected" value="{{review.id}}" class="select-testimonial"></td>
                  <td>{{review.get_full_name}}</td>
                  <td>
                    <div class="star-holder">
                      <div class="star-rating" itemprop="reviewRating" style="width: {{review.qualification}}0px"></div>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td colspan="2">{{review.comment|striptags|truncatewords_html:20}}<td>
                </tr>
              {% endfor %}
              </table>
            </form>
          </div>
          <span class="btn btn-blue lt-btn" ng-click="show_popup=false;change_testimonial()">Aceptar</span>
          <span class="btn btn-red lt-btn" ng-click="show_popup=false">Cancelar</span>
      </div>
    </div>
</div>
{% endblock%}

templates/collaborator/sorry.html
{% load i18n %}
<div class="span9 profile">
    <div class="editor-header">
      <h2>{% trans "Sorry, you not have a clinic" %}</h2>
    </div>
</div>